set echo on
SPOOL rcl_schema_output.txt

--Group id: G033
--Group Name: Rishabh Ray, Yuxin Chen


-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-09-18 15:49:35 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE bookcopy CASCADE CONSTRAINTS;

DROP TABLE bookedition CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE borrowerclass CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE catalogue CASCADE CONSTRAINTS;

DROP TABLE catalogue_author CASCADE CONSTRAINTS;

DROP TABLE catalogue_subject CASCADE CONSTRAINTS;

DROP TABLE lga CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE reserve CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE author (
    author_id   CHAR(4) NOT NULL,
    author_name VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN author.author_id IS
    'Author ID, library assigned in-house code';

COMMENT ON COLUMN author.author_name IS
    'Author full name';

ALTER TABLE author ADD CONSTRAINT author_pk PRIMARY KEY ( author_id );

CREATE TABLE bookcopy (
    book_copy_id              CHAR(15) NOT NULL,
    branch_code               CHAR(3) NOT NULL,
    book_copy_pur_price       VARCHAR2(5) NOT NULL,
    book_copy_counter_reserve VARCHAR2(5) NOT NULL,
    booked_isbn               CHAR(13) NOT NULL
);

COMMENT ON COLUMN bookcopy.book_copy_id IS
    'book copy ID';

COMMENT ON COLUMN bookcopy.branch_code IS
    'unique branch identifier across all branches in all LGA''s';

COMMENT ON COLUMN bookcopy.book_copy_pur_price IS
    'book copy price';

COMMENT ON COLUMN bookcopy.book_copy_counter_reserve IS
    'A flag is added to a book copy to indicate whether it is on counter
 reserve or not.';

COMMENT ON COLUMN bookcopy.booked_isbn IS
    'Book Edition ISBN';

ALTER TABLE bookcopy ADD CONSTRAINT bookcopy_pk PRIMARY KEY ( book_copy_id,
                                                              branch_code );

CREATE TABLE bookedition (
    booked_isbn      CHAR(13) NOT NULL,
    booked_book_type VARCHAR2(3) NOT NULL,
    cata_call_no     VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN bookedition.booked_isbn IS
    'Book Edition ISBN';

COMMENT ON COLUMN bookedition.booked_book_type IS
    'book edition type, should be harcover, loose leaf or papaerback etc. and within 3 words';

COMMENT ON COLUMN bookedition.cata_call_no IS
    'call no of cata';

ALTER TABLE bookedition ADD CONSTRAINT bookedition_pk PRIMARY KEY ( booked_isbn );

CREATE TABLE borrower (
    borrower_no      CHAR(4) NOT NULL,
    borrower_fname   VARCHAR2(30) NOT NULL,
    borrower_lname   VARCHAR2(30) NOT NULL,
    borrower_address VARCHAR2(50) NOT NULL,
    borrower_status  VARCHAR2(10),
    borrower_phone   VARCHAR2(10),
    bc_code          VARCHAR2(5) NOT NULL,
    branch_code      CHAR(3) NOT NULL
);

COMMENT ON COLUMN borrower.borrower_no IS
    'borrower id';

COMMENT ON COLUMN borrower.borrower_fname IS
    'borrower first name';

COMMENT ON COLUMN borrower.borrower_lname IS
    'borrower last name';

COMMENT ON COLUMN borrower.borrower_address IS
    'borrower address';

COMMENT ON COLUMN borrower.borrower_status IS
    'borrower status (can be lost or stolen)';

COMMENT ON COLUMN borrower.borrower_phone IS
    'borrower phone number';

COMMENT ON COLUMN borrower.bc_code IS
    'borrower class ';

COMMENT ON COLUMN borrower.branch_code IS
    'unique branch identifier across all branches in all LGA''s';

ALTER TABLE borrower ADD CONSTRAINT borrower_pk PRIMARY KEY ( borrower_no );

CREATE TABLE borrowerclass (
    bc_code VARCHAR2(5) NOT NULL,
    bc_des  VARCHAR2(50)
);

COMMENT ON COLUMN borrowerclass.bc_code IS
    'borrower class ';

COMMENT ON COLUMN borrowerclass.bc_des IS
    'borrower class description';

ALTER TABLE borrowerclass ADD CONSTRAINT borrowerclass_pk PRIMARY KEY ( bc_code );

CREATE TABLE branch (
    branch_code           CHAR(3) NOT NULL,
    branch_name           VARCHAR2(50) NOT NULL,
    branch_address        VARCHAR2(30) NOT NULL,
    branch_contact_number CHAR(10) NOT NULL,
    manager_id            CHAR(7) NOT NULL,
    lga_code              CHAR(10) NOT NULL
);

COMMENT ON COLUMN branch.branch_code IS
    'unique branch identifier across all branches in all LGA''s';

COMMENT ON COLUMN branch.branch_name IS
    'Branch Name';

COMMENT ON COLUMN branch.branch_address IS
    'Branch Address';

COMMENT ON COLUMN branch.branch_contact_number IS
    'branch contact number';

COMMENT ON COLUMN branch.manager_id IS
    'Manager Identifier ';

COMMENT ON COLUMN branch.lga_code IS
    ' Code of Local Government Agencies';

ALTER TABLE branch ADD CONSTRAINT branch_pk PRIMARY KEY ( branch_code );

CREATE TABLE catalogue (
    cata_call_no        VARCHAR2(30) NOT NULL,
    cata_title          VARCHAR2(100) NOT NULL,
    cata_content        VARCHAR2(30) NOT NULL,
    cata_pub_year       DATE NOT NULL,
    cata_classification VARCHAR2(15) NOT NULL,
    cata_pages          NUMBER(3) NOT NULL,
    cata_readinglevel   CHAR(15),
    cata_language       VARCHAR2(15) NOT NULL,
    cata_edition        VARCHAR2(30) NOT NULL,
    cata_note           CHAR(30) NOT NULL,
    pub_id              CHAR(5) NOT NULL
);

COMMENT ON COLUMN catalogue.cata_call_no IS
    'call no of cata';

COMMENT ON COLUMN catalogue.cata_title IS
    'title of the catalogue';

COMMENT ON COLUMN catalogue.cata_pub_year IS
    'catalouge entry publication year';

COMMENT ON COLUMN catalogue.cata_classification IS
    'as reference, classification of catalouge';

COMMENT ON COLUMN catalogue.cata_readinglevel IS
    'catalogue reading level';

COMMENT ON COLUMN catalogue.cata_language IS
    'catalouge language';

COMMENT ON COLUMN catalogue.cata_edition IS
    'catalouge edition';

COMMENT ON COLUMN catalogue.pub_id IS
    'publisher id, library assign unique in house numerical code';

ALTER TABLE catalogue ADD CONSTRAINT catalogue_pk PRIMARY KEY ( cata_call_no );

CREATE TABLE catalogue_author (
    ca_id        CHAR(7) NOT NULL,
    author_id    CHAR(4) NOT NULL,
    cata_call_no VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN catalogue_author.ca_id IS
    'surrogate key of the catalogue author';

COMMENT ON COLUMN catalogue_author.author_id IS
    'Author ID, library assigned in-house code';

COMMENT ON COLUMN catalogue_author.cata_call_no IS
    'call no of cata';

ALTER TABLE catalogue_author ADD CONSTRAINT catalogue_author_pk PRIMARY KEY ( ca_id );


--  ERROR: UK name length exceeds maximum allowed length(30) 
ALTER TABLE catalogue_author ADD CONSTRAINT catalogue_author_author_id_cata_call_no_un UNIQUE ( author_id,
                                                                                                cata_call_no );

CREATE TABLE catalogue_subject (
    cata_sub_id  CHAR(5) NOT NULL,
    cata_call_no VARCHAR2(30) NOT NULL,
    sub_id       CHAR(4) NOT NULL
);

COMMENT ON COLUMN catalogue_subject.cata_sub_id IS
    'surrogate key of cata_sub';

COMMENT ON COLUMN catalogue_subject.cata_call_no IS
    'call no of cata';

CREATE UNIQUE INDEX catalogue_subject__idx ON
    catalogue_subject (
        sub_id
    ASC );

ALTER TABLE catalogue_subject ADD CONSTRAINT catalogue_subject_pk PRIMARY KEY ( cata_sub_id );


--  ERROR: UK name length exceeds maximum allowed length(30) 
ALTER TABLE catalogue_subject ADD CONSTRAINT catalogue_subject_sub_id_cata_call_no_un UNIQUE ( sub_id,
                                                                                               cata_call_no );

CREATE TABLE lga (
    lga_code          CHAR(10) NOT NULL,
    lga_name          VARCHAR2(50) NOT NULL,
    lga_size          NUMBER(8, 3) NOT NULL,
    lga_contact_name  VARCHAR2(30) NOT NULL,
    lga_contact_phone CHAR(10) NOT NULL
);

COMMENT ON COLUMN lga.lga_code IS
    ' Code of Local Government Agencies';

COMMENT ON COLUMN lga.lga_name IS
    ' Name of Local Government Agencies';

COMMENT ON COLUMN lga.lga_size IS
    ' Local Government Agencies Size in hectares';

COMMENT ON COLUMN lga.lga_contact_name IS
    ' contact name of Local Government Agencies  ';

COMMENT ON COLUMN lga.lga_contact_phone IS
    'Contact phone number of the LGA';

ALTER TABLE lga ADD CONSTRAINT lga_pk PRIMARY KEY ( lga_code );

CREATE TABLE loan (
    loan_out_time        DATE NOT NULL,
    book_copy_id         CHAR(15) NOT NULL,
    branch_code          CHAR(3) NOT NULL,
    loan_due_datetime    DATE NOT NULL,
    loan_return_datetime DATE NOT NULL,
    loan_fine            NUMBER(4, 2) NOT NULL,
    loan_fine_paid_date  DATE,
    borrower_no          CHAR(4) NOT NULL
);

COMMENT ON COLUMN loan.loan_out_time IS
    'loan out time';

COMMENT ON COLUMN loan.book_copy_id IS
    'book copy ID';

COMMENT ON COLUMN loan.branch_code IS
    'unique branch identifier across all branches in all LGA''s';

COMMENT ON COLUMN loan.loan_return_datetime IS
    'loan datetime';

COMMENT ON COLUMN loan.loan_fine_paid_date IS
    'book loan fine paid date by borrower';

COMMENT ON COLUMN loan.borrower_no IS
    'borrower id';

ALTER TABLE loan
    ADD CONSTRAINT loan_pk PRIMARY KEY ( loan_out_time,
                                         book_copy_id,
                                         branch_code );

CREATE TABLE manager (
    manager_id             CHAR(7) NOT NULL,
    manager_fname          VARCHAR2(30) NOT NULL,
    manager_lname          VARCHAR2(30) NOT NULL,
    manager_contact_number VARCHAR2(10) NOT NULL,
    branch_code            CHAR(3) NOT NULL
);

COMMENT ON COLUMN manager.manager_id IS
    'Manager Identifier ';

COMMENT ON COLUMN manager.manager_fname IS
    'Manager firstname';

COMMENT ON COLUMN manager.manager_lname IS
    'manager last name';

COMMENT ON COLUMN manager.manager_contact_number IS
    'manager''s phone number';

COMMENT ON COLUMN manager.branch_code IS
    'unique branch identifier across all branches in all LGA''s';

CREATE UNIQUE INDEX manager__idx ON
    manager (
        branch_code
    ASC );

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( manager_id );

CREATE TABLE publisher (
    pub_id          CHAR(5) NOT NULL,
    pub_name        VARCHAR2(50) NOT NULL,
    pub_des_content VARCHAR2(50) NOT NULL,
    pub_year        DATE NOT NULL
);

COMMENT ON COLUMN publisher.pub_id IS
    'publisher id, library assign unique in house numerical code';

COMMENT ON COLUMN publisher.pub_name IS
    'publisher''s name';

COMMENT ON COLUMN publisher.pub_des_content IS
    'publisher description content';

COMMENT ON COLUMN publisher.pub_year IS
    'publication year';

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( pub_id );

CREATE TABLE reserve (
    reserve_datetime DATE NOT NULL,
    book_copy_id     CHAR(15) NOT NULL,
    branch_code      CHAR(3) NOT NULL,
    borrower_no      CHAR(4) NOT NULL
);

COMMENT ON COLUMN reserve.reserve_datetime IS
    'reserve date time';

COMMENT ON COLUMN reserve.book_copy_id IS
    'book copy ID';

COMMENT ON COLUMN reserve.branch_code IS
    'unique branch identifier across all branches in all LGA''s';

COMMENT ON COLUMN reserve.borrower_no IS
    'borrower id';

ALTER TABLE reserve
    ADD CONSTRAINT reserve_pk PRIMARY KEY ( book_copy_id,
                                            branch_code,
                                            reserve_datetime );

CREATE TABLE subject (
    sub_id      CHAR(4) NOT NULL,
    sub_desc    VARCHAR2(30) NOT NULL,
    cata_sub_id CHAR(5) NOT NULL
);

COMMENT ON COLUMN subject.sub_desc IS
    'subject description';

COMMENT ON COLUMN subject.cata_sub_id IS
    'surrogate key of cata_sub';

CREATE UNIQUE INDEX subject__idx ON
    subject (
        cata_sub_id
    ASC );

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( sub_id );

ALTER TABLE bookcopy
    ADD CONSTRAINT bookcopy_bookedition_fk FOREIGN KEY ( booked_isbn )
        REFERENCES bookedition ( booked_isbn );

ALTER TABLE bookcopy
    ADD CONSTRAINT bookcopy_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE bookedition
    ADD CONSTRAINT bookedition_catalogue_fk FOREIGN KEY ( cata_call_no )
        REFERENCES catalogue ( cata_call_no );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_borrowerclass_fk FOREIGN KEY ( bc_code )
        REFERENCES borrowerclass ( bc_code );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE branch
    ADD CONSTRAINT branch_lga_fk FOREIGN KEY ( lga_code )
        REFERENCES lga ( lga_code );

ALTER TABLE branch
    ADD CONSTRAINT branch_manager_fk FOREIGN KEY ( manager_id )
        REFERENCES manager ( manager_id );

ALTER TABLE catalogue_author
    ADD CONSTRAINT catalogue_author_author_fk FOREIGN KEY ( author_id )
        REFERENCES author ( author_id );

ALTER TABLE catalogue_author
    ADD CONSTRAINT catalogue_author_catalogue_fk FOREIGN KEY ( cata_call_no )
        REFERENCES catalogue ( cata_call_no );

ALTER TABLE catalogue
    ADD CONSTRAINT catalogue_publisher_fk FOREIGN KEY ( pub_id )
        REFERENCES publisher ( pub_id );

ALTER TABLE catalogue_subject
    ADD CONSTRAINT catalogue_subject_catalogue_fk FOREIGN KEY ( cata_call_no )
        REFERENCES catalogue ( cata_call_no );

ALTER TABLE catalogue_subject
    ADD CONSTRAINT catalogue_subject_subject_fk FOREIGN KEY ( sub_id )
        REFERENCES subject ( sub_id );

ALTER TABLE loan
    ADD CONSTRAINT loan_bookcopy_fk FOREIGN KEY ( book_copy_id,
                                                  branch_code )
        REFERENCES bookcopy ( book_copy_id,
                              branch_code );

ALTER TABLE loan
    ADD CONSTRAINT loan_borrower_fk FOREIGN KEY ( borrower_no )
        REFERENCES borrower ( borrower_no );

ALTER TABLE manager
    ADD CONSTRAINT manager_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE reserve
    ADD CONSTRAINT reserve_bookcopy_fk FOREIGN KEY ( book_copy_id,
                                                     branch_code )
        REFERENCES bookcopy ( book_copy_id,
                              branch_code );

ALTER TABLE reserve
    ADD CONSTRAINT reserve_borrower_fk FOREIGN KEY ( borrower_no )
        REFERENCES borrower ( borrower_no );

ALTER TABLE subject
    ADD CONSTRAINT subject_catalogue_subject_fk FOREIGN KEY ( cata_sub_id )
        REFERENCES catalogue_subject ( cata_sub_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             3
-- ALTER TABLE                             35
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0

SPOOL off
set echo off